# Used for Generating Scoreboard
sheetID: "1sCSIA9MPjYXYB8DLqbfDjo02c55sgs195eSvxd2MHQI"
sheetName: "PSEA"
page_filepath: "../season/03/finals.md"
checkpoint: 1
teams: 8

# Used for Generating Team and/or Lobby
team_sheet_id: "1VEN9iFx8N_ZZFTAyc2snPNg3bPYEVZLWP3ToZ_puZAM"
team_sheet_name: "TeamForm"
team_sheet_total_teams: 16
team_sheet_lobby_gid: "" # leave empty if doesn't need multiple lobby
team_sheet_file_path: "../season/03/test.md"
