# Used for Generating Scoreboard
sheetID: "1AE7OcXbmKITjk80L5deReX8231wMbNYOuDBDpcCl6-s"
sheetName: "PSEA"
page_filepath: "../season/03/invitational/score.md"
checkpoint: 0
teams: 8
rank_highlight_count: 3

# Used for Generating Team and/or Lobby
team_sheet_id: "14ZJRhONL8_4quj4rv764Uyl3KVVr1h9Q53BljQ1xhL8"
team_sheet_name: "TeamForm"
team_sheet_total_teams: 8
team_sheet_lobby_gid: "" # leave empty if doesn't need multiple lobby
team_sheet_file_path: "../season/04/garuda/teams.md"
