# Used for Generating Scoreboard
# sheetID: "1CQXdXDB-GXjHtS6JIJdd7w-MQu_N53aqz9lfedA_lIo"
sheetID: "1DStFu5dzrK1Z53VBjE9FGirj7DxOjgBvxoudkUR7rXA"
sheetName: "PSEA"
page_filepath: "../season/04/qualifiers.md"
checkpoint: 0
teams: 8
rank_highlight_count: 5

# Used for Generating Team and/or Lobby
team_sheet_id: "1Kako9sV8s_pJdB65FqiaqerOSmg-FUSa9oJbaE-_N3A"
team_sheet_name: "TeamForm"
# team_sheet_total_teams: 8
team_sheet_total_teams: 8
team_sheet_lobby_gid: "" 
team_sheet_file_path: "../season/04/teams.md"
