
# https://docs.google.com/spreadsheets/d/1K3jKsSzjc1ssmJVFDPFlOqAoxAOJiLGslJ51yH9TajA/edit?usp=sharing

sheetID: "1e5XGJddjZuGTK0HNeQUOZsQPzJ2pO6ayjwDCKKS3Upo"
sheetName: "PSEA"
page_filepath: "../sea_fun_format/0925/finals.md"
checkpoint: 0
teams: 8

lobby: 1
lobby1:
- RainyChisu
- SungJinWoo 
- Lapis
- Minor 
- FISH
- Still In Love
- Adogna
- ZibubsMyWife
lobby2:
- GyooOF
- WingTomZai
- Oreo
- KingTangDoge
- Dentge
- CEPU 
- aigooo
- BuffTacArmor
