
sheetID: "1IExwAjBweKnrwu-VPavz7mJg7xwlG4BK8qjggF4j5z0"
sheetName: "PSEA"
page_filepath: "../season/04/invitational/score.md"
checkpoint: 0
teams: 8

lobby: 1
lobby1:
- 
- 
- 
- 
- 
- 
- 
- 
lobby2:
- 
- 
- 
- 
- 
- 
- 
- 

